[package]
name = "get"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2"
quote = "1.0.23"
proc-macro2 = "1.0.51"
if_chain = "=1.0.2"

[dev-dependencies]
trybuild = "1"